// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.png" {
  /**
   * A path to the PNG file
   */
  const path: `${string}.png`;
  export = path;
}

declare module "*.wav" {
  /**
   * A path to the WAV file
   */
  const path: `${string}.wav`;
  export = path;
}

declare module "*.ogg" {
  /**
   * A path to the OGG file
   */
  const path: `${string}.ogg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "*.css" {
  /**
   * Side-effect CSS imports are handled by the bundler.
   */
  const css: string;
  export default css;
}
